palakm/cal/urls.py
from django.conf.urls import url
from . import views

app_name = 'cal'
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/new/$', views.event, name='event_new'),
    url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
]

palakm/palak/urls.py
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from palak.views import budget,stage1,budget_stage1,update_stage1,updated_stage1,datatable,stages2,script_input,update_stage2_budget
app_name = 'palak'

urlpatterns = [
    path('',views.homepage,name="homepage"),
    path('script_info/',views.script_info,name="script_info"),
    path('character/',views.character,name="character"),
    path('screenplays/',views.screenplays,name="screenplays"),
    path('character_edit/',views.character_edit,name="character_edit"),
    path('budget/', views.budget, name="test"),
	url(r'^run-sh/$', views.index, name='run_sh'),
    path('check/', views.checkbox, name="check"),
	path('update/', views.update_budget, name="update"),
	path('datatable/', views.datatable, name="datatable"),
	path('updated/', views.updated_budget, name="update2"),
	path('stage2/', views.stages2, name="stages2"),
    # path('stage2/', views.stage1_saved, name="stage1_saved"),
	path('stage2/update', views.update_stage2, name="stage2.1"),
	path('update_2/', views.update_stage2_budget, name="update_stage2"),
	path('script/', views.script_input, name="script"),
	path('update/stage1', views.update_stage1, name="update1"),
	
	path('budget/stage1', views.stage1, name="stage1"),
	path('updated/stage1', views.updated_stage1, name="stage1.1"),
   
] 

palakm/palakm/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('users.urls')),
    path('',include('palak.urls')),
    path('cal/', include('cal.urls')),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('social-accounts/', include('allauth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

palakm/users/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name = 'users'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('forgot_password/', views.forgot_password, name='forgot-password'),
    path('logout', views.logoutUser, name='logout')
]

palakm/palak/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.core.files.storage import FileSystemStorage
from django.template import RequestContext
from django.http import HttpResponseRedirect
from palak.models import Script_info
from palak.models import Character_edit


def homepage(request):   
    return render(request,'palak/pages/homepage.html') 

def screenplays(request):  
    msg = Script_info.objects.all() 
    
    return render(request,'palak/pages/screenplays.html',{"msg":msg}) 

def character(request):   
    return render(request,'palak/pages/character.html') 

def character_edit(request):
    if request.method=="POST":
        print("request",request.FILES)
        character_image =request.FILES['character_image']
        character_name = request.POST.get('character_name', '')
        gender = request.POST.get('gender', '')
        age_group = request.POST.get('age_group', '')
        music = request.POST.get('music', '')
        print("music",music)
        

        Character_edit.objects.create( character_image=character_image,character_name=character_name,gender=gender,age_group=age_group,music=music)  
    return render(request,'palak/pages/character_edit.html') 

def script_info(request):
    if request.method=="POST":
        
        script_title = request.POST.get('script_title', '')
        Author_name  = request.POST.get('Author_name', '')
        genre = request.POST.getlist('genre[]', '')
        language_of_action_line = request.POST.get('language_of_action_line', '')
        language_of_dialogues = request.POST.get('language_of_dialogues', '')
        script_written_in = request.POST.get('script_written_in', '')
        time = request.POST.get('time', '')
        country = request.POST.get('country', '')
        city = request.POST.get('city', '')
        scriptfile = request.FILES['scriptfile']

        Script_info.objects.create(script_title=script_title, Author_name=Author_name, genre=genre,language_of_action_line=language_of_action_line,
        language_of_dialogues=language_of_dialogues,script_written_in=script_written_in,time =time ,
        country=country,city=city,scriptfile=scriptfile)
        
        
    return render(request, 'palak/pages/script_info.html')

def budget(request):
   
   if request.method == 'POST' and request.FILES['Choose Script']:
        myfile = request.FILES['Choose Script']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)
        uploaded_file_url=uploaded_file_url.replace('/media/','')
        
        file=request.POST.getlist('mycheckboxname')
        currency=request.POST.get('currency1')
        time=request.POST.get('time1')
        city=request.POST.get('city1')
        language=request.POST.get('language1')
        date=request.POST.get('date1')
        budget=request.POST['text1']
        
        return render(request, 'palak/pages/budget1.html', {"budget":budget,"city":city,"curr":currency,"time":time,"date":date,"language":language,'duration':time,'file':file,'uploaded_file_url': uploaded_file_url})
   
   return render(request,'palak/pages/budget.html')  

def stage1(request):
   
    if request.method == 'POST':
            #if request.POST.get('text7') and request.POST.get('text8') and request.POST.get('text9') and request.POST.get('text10') and request.POST.get('text11') and request.POST.get('text12') and request.POST.get('text13') and request.POST.get('text14') and request.POST.get('text15') :
           post=Budget()
           post.Actors= float(request.POST['text7'])
           post.Other_Actors= float(request.POST['text8'])
           post.Production= request.POST['text9']
           post.Director= request.POST['text10']
           post.Producer= request.POST['text11']
           post.post_production= request.POST['text12']
           post.Legal= request.POST['text13']
           post.Marketing= request.POST['text14']
           post.Miscellaneous= request.POST['text15']
           post.Total_Budget=request.POST['text1']
           post.Project=request.POST['project']
           post.User=request.user
           post.save()
           return render(request, 'palak/pages/stage1.html')  
		
    else :
       total_budget=int(request.GET['text1'])
       currency=request.GET.get('text3')
       project=request.GET.get('project')
       percentage_list=[0.2,0.05,0.3,0.05,0.05,0.05,0.02,0.27,0.01]
       lead_actor= int(0.2*total_budget)
       other_actors=int(0.05*total_budget)
       production=int(0.3*total_budget)
       director=int(0.05*total_budget)
       producer=int(0.05*total_budget)
       post_production=int(0.05*total_budget)
       legal=int(0.02*total_budget)
       marketing=int(0.27*total_budget)
       miscellaneous=int(0.01*total_budget)
       context={'a':lead_actor,'b':other_actors,'c':production,'d':director,'e':producer,'f':post_production,'g':legal,'h':marketing,'i':miscellaneous,'curr':currency,'tb':total_budget,'project':project}
	
    return render(request,'palak/pages/stage1.html',context)

def update_stage1(request):
    total_budget=int(request.GET['text1'])
    currency=request.GET.get('text3')
    currency=request.GET.get('currency')
    time=request.GET.get('time')
    city=request.GET.get('city')
    language=request.GET.get('language')
    date=request.GET.get('date')
    percentage_list=[20/100,5/100,30/100,4/100,4/100,5/100,2/100,24/100,1/100,5/100]
    
    list=[20*total_budget/100,5*total_budget/100,30*total_budget/100,4*total_budget/100,4*total_budget/100,5*total_budget/100,2*total_budget/100,24*total_budget/100,1*total_budget/100,5*total_budget/100]
  
    
	    
    lead_actor1=float(request.GET['text7'])
    other_actors1=float(request.GET['text8'])
    production1=float(request.GET['text9'])
    director1=float(request.GET['text10'])
    producer1=float(request.GET['text11'])
    post_production1=float(request.GET['text12'])
    legal1=float(request.GET['text13'])
    marketing1=float(request.GET['text14'])
    miscellaneous1=float(request.GET['text15'])
    writer1=float(request.GET['writer'])
    list1=[lead_actor1,other_actors1,production1,director1,producer1,post_production1,legal1,marketing1,miscellaneous1,writer1]
    
	
    dif=[]
    sum1=0
    sum_initial=0
    percentage=[]
    for i in range (0,10):
        percentage.append(0)
    
    for i in range (0,10):
        dif.append(list[i]-list1[i])
		
    if sum(list)<sum(list1):
       for i in range (0,10):
           if dif[i]!=0:
              percentage[i]=list1[i]/total_budget
              sum1=sum1+list1[i]/total_budget
              sum_initial=sum_initial+percentage_list[i]
       for i in range (0,10):
           if dif[i]==0:
              percentage[i]=percentage_list[i]*(1-sum1)/(1-sum_initial)
       for i in range (0,10):  
           list[i]=percentage[i]*total_budget	
       differ=sum(list)-total_budget
       lead_actor=round(list[0])
       other_actors=round(list[1])
       production=round(list[2])
       director=round(list[3])
       producer=round(list[4])
       post_production=round(list[5])
       legal=round(list[6])
       marketing=round(list[7])-round(differ)
       miscellaneous=round(list[8])
       writer=round(list[9])
	
    if sum(list)>=sum(list1):
       for i in range(0,10):
           if dif[i]!=0:
              for j in range(0,10):
	                list[j]=list1[j]+((percentage_list[j])/(1-percentage_list[i]))*dif[i]
       for i in range(0,10):
           if list[i]<0:
              list[i]=0
    
	   
       for i in range(0,10):
          if dif[i]!=0:
	          list[i]=list1[i]
       dif.clear()
       differ=sum(list)-total_budget
	   
       lead_actor=round(list[0])
       other_actors=round(list[1])
       production=round(list[2])
       director=round(list[3])
       producer=round(list[4])
       post_production=round(list[5])
       legal=round(list[6])
       marketing=round(list[7])-round(differ)
       miscellaneous=round(list[8])
       writer=round(list[9])
	
	#if dif[0]!=0:
        #lead_actor=int(request.GET['text7'])
        #other_actors=int(0.05*total_budget+(0.2*0.05263+0.05)*dif[0])
        #production=int(0.3*total_budget+(0.2*0.4285+0.3)*dif[0])
        #director=int(0.05*total_budget+(0.2*0.05263+0.05)*dif[0])
        #producer=int(0.05*total_budget+(0.2*0.05263+0.05)*dif[0])
        #post_production=int(0.05*total_budget+(0.2*0.05263+0.05)*dif[0])
        #legal=int(0.02*total_budget+(0.2*0.02040+0.02)*dif[0])
        #marketing=int(0.27*total_budget+(0.27*0.37+0.27)*dif[0])
        #miscellaneous=int(0.01*total_budget+(0.01*0.01010+0.01)*dif[0])
   
	
    
    
    context={"writer":writer,"city":city,"curr":currency,"time":time,"date":date,"language":language,'duration':time,'a':lead_actor,'b':other_actors,'c':production,'d':director,'e':producer,'f':post_production,'g':legal,'h':marketing,'i':miscellaneous,'curr':currency,'tb':total_budget}
	
    return render(request,'palak/pages/stage1.1.html',context)

	
def updated_stage1(request):
    total_budget=int(request.GET['text1'])
    currency=request.GET.get('text3')
    percentage_list=[0.2,0.05,0.3,0.05,0.05,0.05,0.02,0.27,0.01]
    currency=request.GET.get('currency')
    time=request.GET.get('time')
    city=request.GET.get('city')
    language=request.GET.get('language')
    date=request.GET.get('date')
    list3=['text16','text17','text18','text19','text20','text21','text22','text23','text24']
    list2=[]
    for i in range(0,9):
	      list2.append(float(request.GET[list3[i]]))
    
    
    lead_actor1=float(request.GET['text7'])
    other_actors1=float(request.GET['text8'])
    production1=float(request.GET['text9'])
    director1=float(request.GET['text10'])
    producer1=float(request.GET['text11'])
    post_production1=float(request.GET['text12'])
    legal1=float(request.GET['text13'])
    marketing1=float(request.GET['text14'])

palakm/palak/templates/login/signin.html
{% load static %}
{% load socialaccount %}
{% providers_media_js %}

<!DOCTYPE html>

<html lang="en">
	<!--begin::Head-->
	<head><base href="../../../../">
		<meta charset="utf-8" />
		<title>Sign In | Keenthemes</title>
		<meta name="description" content="Singin page example" />
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
		<link rel="canonical" href="https://keenthemes.com/metronic" />
		<!--begin::Fonts-->
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" />
		<!--end::Fonts-->
		<!--begin::Page Custom Styles(used by this page)-->
		<link href="{% static 'palak/assets/css/pages/login/login-3.css' %}" rel="stylesheet" type="text/css" />
		<!--end::Page Custom Styles-->
		<!--begin::Global Theme Styles(used by all pages)-->
		<link href="{% static 'palak/assets/plugins/global/plugins.bundle.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% static 'palak/assets/plugins/custom/prismjs/prismjs.bundle.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% static 'palak/assets/css/style.bundle.css' %}" rel="stylesheet" type="text/css" />
		<!--end::Global Theme Styles-->
		<!--begin::Layout Themes(used by all pages)-->
		<link href="{% static 'palak/assets/css/themes/layout/header/base/light.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% static 'palak/assets/css/themes/layout/header/menu/light.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% static 'palak/assets/css/themes/layout/brand/dark.css' %}" rel="stylesheet" type="text/css" />
		<link href="{% static 'palak/assets/css/themes/layout/aside/dark.css' %}" rel="stylesheet" type="text/css" />
		<!--end::Layout Themes-->
		<link rel="shortcut icon" href="{% static 'palak/assets/media/logos/favicon.ico' %}" />
	</head>
	<!--end::Head-->
	<!--begin::Body-->
	<body id="kt_body" class="header-fixed header-mobile-fixed subheader-enabled subheader-fixed aside-enabled aside-fixed aside-minimize-hoverable page-loading">
		<!--begin::Main-->
		<div class="d-flex flex-column flex-root">
			<!--begin::Login-->
			

				<!--begin::Content-->
				<div class="login-content flex-row-fluid d-flex flex-column p-10">
					<!--begin::Top-->
					
					<div class="text-right d-flex justify-content-center">
						<img style="width: 400px;"  src="{% static 'palak/assets/media/svg/illustrations/login-visual-5.svg'  %}">
						<div class="top-signin text-right d-flex justify-content-end pt-5 pb-lg-0 pb-10">
							
							<span class="font-weight-bold text-muted font-size-h4">Having issues?</span>
							<a href="javascript:;" class="font-weight-bold text-primary font-size-h4 ml-2" id="kt_login_signup">Get Help</a>
						</div>
					</div>
					<!--end::Top-->
					<!--begin::Wrapper-->
					<div class="d-flex flex-row-fluid flex-center">
						<!--begin::Signin-->
						<div class="login-form">



							<!--begin::Form-->
							<form class="form" method="POST">
								{% csrf_token %}
								<!--begin::Title-->
								<div class="pb-5 pb-lg-15">
									<h3 class="font-weight-bolder text-dark font-size-h2 font-size-h1-lg">Sign In</h3>
									<div class="text-muted font-weight-bold font-size-h4">New Here?
									<a href="{% url 'users:signup' %}" class="text-primary font-weight-bolder">Create Account</a></div>
								</div>
								<!--begin::Title-->
								<!--begin::Form group-->
								<div class="form-group">
									<label class="font-size-h6 font-weight-bolder text-dark">UserName</label>
									<input type="text" name="username" placeholder="email" class="form-control h-auto py-7 px-6 rounded-lg border-0" />
								</div>
								<!--end::Form group-->
								<!--begin::Form group-->
								<div class="form-group">
									<div class="d-flex justify-content-between mt-n5">
										<label class="font-size-h6 font-weight-bolder text-dark pt-5">Password</label>
										<a href="{% url 'users:forgot-password' %}" class="text-primary font-size-h6 font-weight-bolder text-hover-primary pt-5">Forgot Password ?</a>
									</div>
									<input type="password" name="password" placeholder="Password"  class="form-control h-auto py-7 px-6 rounded-lg border-0"  />
								</div>
								{% for message in messages %}
									<p id="messages">{{message}}</p>
								{% endfor %}
<div class="text-center my-5">
								<input value="signin" type="submit"  class="btn btn-primary font-weight-bolder font-size-h6 px-8 py-4 my-3 mr-3">
	<br/>
	<p class="font-size-h5 font-weight-bold m-5">Or continue with</p>
								<!--end::Form group-->
								<a href="{% provider_login_url 'google' %}"><img class="m-1" src="{% static 'palak/assets/media/icons/google.png' %}"  height="30px" width="30px"></a>
								<a href="{% provider_login_url 'facebook' method='js_sdk' %}"><img class="m-1" src="{% static 'palak/assets/media/icons/facebook.png' %}"  height="30px" width="30px"></a>
								<a href=""><img class="m-1" src="{% static 'palak/assets/media/icons/twitter.png' %}"  height="30px" width="30px"></a>
</div>

              <p class=" text-center" >By Signing In, you agree to our <a href="#" class="font-weight-bold">Terms of
                Services <span class="font-weight-bolder ">and</span> Privacy Policy.</a></p>
								{% comment %}
								<!--begin::Action-->
								<div class="pb-lg-0 pb-5">

									<button type="button" class="btn btn-light-primary font-weight-bolder px-8 py-4 my-3 font-size-lg">
									<span class="svg-icon svg-icon-md">
										<!--begin::Svg Icon | path:assets/media/svg/social-icons/google.svg-->
										<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 20 20" fill="none">
											<path d="M19.9895 10.1871C19.9895 9.36767 19.9214 8.76973 19.7742 8.14966H10.1992V11.848H15.8195C15.7062 12.7671 15.0943 14.1512 13.7346 15.0813L13.7155 15.2051L16.7429 17.4969L16.9527 17.5174C18.879 15.7789 19.9895 13.221 19.9895 10.1871Z" fill="#4285F4" />
											<path d="M10.1993 19.9313C12.9527 19.9313 15.2643 19.0454 16.9527 17.5174L13.7346 15.0813C12.8734 15.6682 11.7176 16.0779 10.1993 16.0779C7.50243 16.0779 5.21352 14.3395 4.39759 11.9366L4.27799 11.9466L1.13003 14.3273L1.08887 14.4391C2.76588 17.6945 6.21061 19.9313 10.1993 19.9313Z" fill="#34A853" />
											<path d="M4.39748 11.9366C4.18219 11.3166 4.05759 10.6521 4.05759 9.96565C4.05759 9.27909 4.18219 8.61473 4.38615 7.99466L4.38045 7.8626L1.19304 5.44366L1.08875 5.49214C0.397576 6.84305 0.000976562 8.36008 0.000976562 9.96565C0.000976562 11.5712 0.397576 13.0882 1.08875 14.4391L4.39748 11.9366Z" fill="#FBBC05" />
											<path d="M10.1993 3.85336C12.1142 3.85336 13.406 4.66168 14.1425 5.33717L17.0207 2.59107C15.253 0.985496 12.9527 0 10.1993 0C6.2106 0 2.76588 2.23672 1.08887 5.49214L4.38626 7.99466C5.21352 5.59183 7.50242 3.85336 10.1993 3.85336Z" fill="#EB4335" />
										</svg>
										<!--end::Svg Icon-->
									</span>Sign in with Google</button>
								</div>
								<!--end::Action-->
								{% endcomment %}

							</form>
							<!--end::Form-->

						</div>
						<!--end::Signin-->
					</div>
					<!--end::Wrapper-->
				</div>
				<!--end::Content-->
			</div>
			<!--end::Login-->
		</div>
		<!--end::Main-->
		<script>var HOST_URL = "https://preview.keenthemes.com/metronic/theme/html/tools/preview";</script>
		<!--begin::Global Config(global config for global JS scripts)-->
		<script>var KTAppSettings = { "breakpoints": { "sm": 576, "md": 768, "lg": 992, "xl": 1200, "xxl": 1400 }, "colors": { "theme": { "base": { "white": "#ffffff", "primary": "#3699FF", "secondary": "#E5EAEE", "success": "#1BC5BD", "info": "#8950FC", "warning": "#FFA800", "danger": "#F64E60", "light": "#E4E6EF", "dark": "#181C32" }, "light": { "white": "#ffffff", "primary": "#E1F0FF", "secondary": "#EBEDF3", "success": "#C9F7F5", "info": "#EEE5FF", "warning": "#FFF4DE", "danger": "#FFE2E5", "light": "#F3F6F9", "dark": "#D6D6E0" }, "inverse": { "white": "#ffffff", "primary": "#ffffff", "secondary": "#3F4254", "success": "#ffffff", "info": "#ffffff", "warning": "#ffffff", "danger": "#ffffff", "light": "#464E5F", "dark": "#ffffff" } }, "gray": { "gray-100": "#F3F6F9", "gray-200": "#EBEDF3", "gray-300": "#E4E6EF", "gray-400": "#D1D3E0", "gray-500": "#B5B5C3", "gray-600": "#7E8299", "gray-700": "#5E6278", "gray-800": "#3F4254", "gray-900": "#181C32" } }, "font-family": "Poppins" };</script>
		<!--end::Global Config-->
		<!--begin::Global Theme Bundle(used by all pages)-->
		<script src="{% static 'palak/assets/plugins/global/plugins.bundle.js' %}"></script>
		<script src="{% static 'palak/assets/plugins/custom/prismjs/prismjs.bundle.js' %}"></script>
		<script src="{% static 'palak/assets/js/scripts.bundle.js' %}"></script>
		<!--end::Global Theme Bundle-->
		<!--begin::Page Scripts(used by this page)-->
		<script src="{% static 'palak/assets/js/pages/custom/login/login-3.js' %}"></script>
		<!--end::Page Scripts-->
	</body>
	<!--end::Body-->
</html>